### ISSUE TITLE
Can we move `default_whitelist.yml` to `.theia`?

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/appdev_template#163]
Since we've started marrying ourselves to gitpod with moving what used to be `grades.yml` into `.theia/`, can we also move `default_whitelist.yml` there?

(Trying to stop the creeping scourge of dotfiles in the root folder.)

**Comment by jelaniwoods** [comment]
I wonder, do we even _need_ `default_whitelist.yml` anymore? The purpose of this was for better errors to work in development using the `console_ip_whitelist` gem. On Gitpod, this didn't work since ips of workspaces were rotated too regularly so we whitelisted _all_ or Gitpod with
```
BetterErrors::Middleware.allow_ip! '10.138.0.0/16'
```

So I don't think we even need the yml file anymore.

**Comment by raghubetina** [comment]
@jelaniwoods Makes sense to me. Shall we drop console_ip_whitelist entirely then?

**Comment by jelaniwoods** [comment]
@raghubetina Yes, I think that makes sense. I'll update the PR.
